spring:
  main:
    web-application-type: none
  application:
    name: social-scheduler
  datasource:
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/${DATABASE:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driverClassName: org.postgresql.Driver
  rabbitmq:
    host: ${RABBIT_HOST:127.0.0.1}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}

logging:
  level:
    org: ERROR
