services:
  rabbit:
    build:
      context: .
      dockerfile: rabbitmq/Dockerfile
    ports:
      - 5672:5672
      - 8080:15672
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres